openapi: 3.0.0
info:
  version: 1.0.0
  contact:
    name: SFKB Brukerstøtte
    url: https://www.kartverket.no/Prosjekter/Sentral-felles-kartdatabase/brukerstotte/
  title: Oppdateringsgrensesnitt for SFKB
  description: |
    # NGIS-OpenAPI
    
    Grov oversikt over funksjonalitet:
      - Hente liste over tilgjengelige datasett 
      - Hente metadata for et bestemt datasett
      - Hente data fra et bestemt datasett
        - Med lesetilgang eller skrivetilgang (medfører låsing)
          - områdebegrensning
          - egenskapsspørring (begrenset i første versjon til bygningsnummer eller lokalid)
      - Lagre data til et bestemt datasett
        - Operasjoner som håndteres: nytt objekt, endre objekt og slett objekt
    
    ## Generelle prinsipper for systemet

    ### Delt geometri
    
    Flater består av avgrensningslinjer som ligger lagret som egne objekter. På den måten kan en linje avgrense ingen, én eller flere flater.
    Det er likevel slik at flater hentes ut og lagres med egen geometri for å gjøre det enklere å tegne opp datene, men ved endring av (delte) linjer og flater
    må det tas hensyn til delt geometri. Forsøk på endring av linje eller flate uten tilsvarende endring av evt. delt geometri vil bli avvist av systemet.

    ### Låsing
    
    Dette er nærmere beskrevet i de aktuelle kallene.

    Foreløpig er det kun `user_lock` som er støttet. Det betyr at data må hentes ut med `user_lock` før de kan sendes inn med endringer.
    
    ### Porsjonering
    
    All uthenting av feature-objekter vil kunne bli porsjonert av serveren, se `limit`-parameteret. 
    
    ### Koordinatsystemer og transformasjon
    
    Dersom annet koordinatsystem enn det som ligger i dataset skal brukes (se `GET /datasets/{datasetId}`) må koordinatsystem angis med `crs_EPSG`-parameteret. Dette styrer data som sendes inn, data som hentes ut og koordinatsystemet i `bbox`-parameteret i kallet. For å bytte rekkefølge på aksene brukes `crs_normalized_for_visualization`-parameteret.
    
    ### Historikk og historiske endringer
    
    Det er mulig å hente ut data for et gitt tidspunkt (for hele datasettet eller begrenset til et område, et objekt etc.). Se etter parameteret `dataset_at`.
    
    Det er også mulig å hente ut historikken som endringer, f.eks som endringer fra et tidligere uthentet område, objekt eller helt dataset. Se etter parameteret `dataset_modified`.
    
servers:
  - description: Test-server Norkart
    url: https://qmsrest.westeurope.cloudapp.azure.com:8080/v1/
  - description: Server hos Kartverket
    url: https://openapi-test.kartverket.no/v1/
    

security:
  - basicAuth: []  # <-- use the same name here
  
tags:
  - name: metadata
    description: "Informasjon om dataset som brukeren har tilgang til"
  - name: features
    description: "Operasjoner på features i et bestemt dataset"
  - name: locks
    description: "Behandling av features som brukeren har låst"
paths:
  /datasets:
    get:
      tags:
       - metadata
      summary: Hent liste over tilgjengelige dataset
      description: |
        Henter en liste over alle dataset som brukeren har lese- eller skrivetilgang til. 
        Dersom brukeren ikke har tilgang til noen dataset, returneres en tom liste.
      operationId: getDatasets
      parameters:        
        - $ref: '#/components/parameters/clientHeaderParam'
      responses:
        '200':      # Response
          description: OK
          content:  # Response body
            application/vnd.kartverket.ngis.datasets+json:  # Media type
              schema: 
                $ref: '#/components/schemas/DatasetList'    # Reference to object definition
        '401':
          description: Gyldig autentisering av brukeren mangler eller er ugyldig
        '406':
          description: Formatet klienten ønsker på data er ugyldig. Klienten har f.eks en ugyldig Accept-header og kan ikke motta data på et format som serveren kan levere
        '500':
          description: Intern feil på serveren
        '501':
          description: Intern feil på serveren (kallet er ikke implementert)
        '503':
          description: Intern feil på serveren (tjenesten er utilgjengelig)
  /datasets/{datasetId}:
    get:
      tags:
       - metadata
      summary: Hent metadata for et bestemt dataset
      description: |
        Henter utvidet informasjon om et bestemt dataset. 
        Her ligger all informasjon som kommer ut i listen over dataset, og i tillegg en del ekstra informasjon som enten er unødvendig eller for tung å ha med i listen over dataset.
      operationId: getDatasetMetadata
      parameters:
        - $ref: '#/components/parameters/clientHeaderParam'
        - $ref: '#/components/parameters/datasetIdParam'
        - $ref: '#/components/parameters/crsEPSGParam'
        - $ref: '#/components/parameters/crsNormalizedForVisualizationParam'
      responses:
        '200':      # Response
          description: OK
          content:  # Response body
            application/vnd.kartverket.ngis.dataset+json:  # Media type
              schema: 
                $ref: '#/components/schemas/Dataset'    # Reference to object definition
              examples:
                explicitSame:
                  summary: Implisitt crs_EPSG-parameter
                  description: |
                    Dersom klienten ikke ber om et annet referansesystem enn datasetets referansesystem, leveres dataene i samme koordinatesystem som datasetet er lagret.
                  value:
                    id: '07b59e3d-a4b6-4bae-ac4c-664d3dc3d778'
                    name: 'AR5_22'
                    resolution: 0.001
                    crs_EPSG: 5972
                    access: read_write
                    dataset_last_modified: '2021-03-15T09:57:41.915094000Z'
                    bbox:
                      ll: [322361.85, 6424859.18]
                      ur: [637396.44, 7296440.28]
        '401':
          description: Gyldig autentisering av brukeren mangler eller er ugyldig
        '406':
          description: Formatet klienten ønsker på data er ugyldig. Klienten har f.eks en ugyldig Accept-header og kan ikke motta data på et format som serveren kan levere
        '403':
          description: Ugyldig brukernavn og/eller passord
        '404':
          description: Fant ikke angitt dataset
        '500':
          description: Intern feil på serveren
        '501':
          description: Intern feil på serveren (kallet er ikke implementert)
        '503':
          description: Intern feil på serveren (tjenesten er utilgjengelig)
  /datasets/{datasetId}/features:
    get:
      tags:
       - features
      summary: Hent ut features fra et dataset
      description: >-
        Henter en liste over alle dataset som brukeren har lese- eller skrivetilgang til.
      operationId: getDatasetFeatures
      parameters:
        - $ref: '#/components/parameters/clientHeaderParam'
        - $ref: '#/components/parameters/datasetIdParam'
        - $ref: '#/components/parameters/lockingParam'
        - $ref: '#/components/parameters/bboxParam'
        - $ref: '#/components/parameters/crsEPSGParam'
        - $ref: '#/components/parameters/crsNormalizedForVisualizationParam'
        - $ref: '#/components/parameters/referencesParam'
        - $ref: '#/components/parameters/limitParam'
        - $ref: '#/components/parameters/cursorParam'
        - in: query
          name: query
          schema:
            type: string
          description: |
            ### Filter på egenskaper og/eller objekttype for å begrense hvilke features som hentes ut.
            
            Spørrespråket er basert på [RQL](https://github.com/persvr/rql).
            
            Foreløpig støttes kun `eq` og `in` for bestemte objekttyper og egenskaper.
            
            Eksemplene inneholder alle støttede spørringer.
          examples:
            bygningsnummer:
              value: 'eq(Bygning/bygningsnummer,1234)'
              summary: Spørring etter ett bestemt bygningsnummer for objekttypen Bygning
              description: |
               Spørringen henter ut alle objekter med objekttypen Bygning med egenskapen bygningsnummer = 1234.
            lokalid:
              value: 'eq(*/identifikasjon/lokalid,000a7b9b-7088-482f-a3cf-9761b97a54b6)'
              summary: Spørring etter ett bestemt objekt med gitt lokalid
              description: |
                Når et objekt hentes ut med lokalid er det normalt ikke nødvendig å filtrere på objekttype, derfor er objekttypen angitt med `*`.
            lokalid_multi:
              value: 'in(*/identifikasjon/lokalid,000a7b9b-7088-482f-a3cf-9761b97a54b6,023a7b9b-7088-482f-a3cf-9761b9700000)'
              summary: Spørring etter flere objekter med lokalid
              description: |
                Når objekt(er) hentes ut med lokalid er det normalt ikke nødvendig å filtrere på objekttype, derfor er objekttypen angitt med `*`.
            feature_type:
              value: 'eq(*,Bygning)'
              summary: Spørring etter alle objekter med en bestemt objekttype
              description: |
                Vi bruker `*` for å angi at vi kun filtrerer på objekttype.
            feature_type_multi:
              value: 'in(*,Bygning,AnnenBygning)'
              summary: Spørring etter flere objekter med lokalid
              description: |
                Vi bruker `*` for å angi at vi kun filtrerer på objekttype.
        - in: query
          name: dataset_at
          schema:
            type: string
            format: date-time
          description: |
            Angir hvilket tidspunkt man ønsker å hente ut data på.
            
            Kan kombineres med andre parametre, f.eks `bbox`, `query`, `crs_EPSG` osv.
        - in: query
          name: dataset_modified
          schema:
            type: string
          description: |
            ### Intervall for uthenting av historiske endringer
            
            Må kombineres med `Accept`-header med samme dataformat som ved lagring av endringer.
            
            Kan kombineres med andre parametre, f.eks `bbox`, `query`, `crs_EPSG` osv.
            
            Formatet er <fra>/<til> hvor `..` er det samme som hhv. "fra og med første endring" eller "til og med siste endring".
            
            Hvis man ikke angir `..` må man angi et tidspunkt i henhold til ISO 8601, eks. `2020-01-30 12:13:14`. Man kan også angi høyere oppløsning enn sekund og tidssone med `Z` (betyr UTC) eller offset f.eks `+02:00`.
            
          examples:
            open_range:
              value: '../..'
              summary: Alle endringer i datasetet fra og med første og til og med siste.
            all_changes_since:
              value: '../..'
              summary: Alle endringer i datasetet fra gitt tidspunkt. Dette kan f.eks komme fra datasetets `dataset_last_modified` eller `Dataset-Last-Modified`-headeren hvis man ønsker å hente ut alle endringer etter hvert som de blir gjort i datasetet.
            january_2020:
              value: '2020-01-01 00:00:00/2020-01-31 23:59:59.999999'
              summary: Spørring etter alle endringer i januar 2020
      responses:
        '200':      # Response
          description: OK
          headers:
            Dataset-Last-Modified:
              schema:
                type: string
                format: date-time
              description: Tidspunkt for siste endring som kan brukes ved uthenting av historiske endringer gjort på objekter etter denne lesingen.
          content: # Response body
            
            application/vnd.kartverket.sosi+gml; version=1.0:
             schema:
              type: object
             examples: 
              singlePoint:
                summary: |
                  Eksempel på uthentet punkt
                externalValue: 'https://raw.githubusercontent.com/kartverket/SFKB-API/master/spec/examples/point/Bygning.xml'
              singleLineString:
                summary: | 
                  Eksempel på uthentet linje
                externalValue: 'https://raw.githubusercontent.com/kartverket/SFKB-API/master/spec/examples/linestring/Mønelinje.xml'
              simplePolygon:
                summary: Eksempel på uthentet flate som refererer én enkel avgrensningslinje
                description: |
                  Representasjonspunktet som ligger inne i flaten ligger i `geometry_properties` som `position`.

                  Lenkene til avgrensningslinjer (bruker linjenes lokalid) ligger i `geometry_properties` under `exterior`. 

                  Ytre avgrensningslinjer i en flate må ha retning mot klokka (CCW) og indre avgrensningslinjer må ha retning med klokka.
                  Det betyr at noen av linjene som brukes må brukes i motsatt retning - dette gjøres ved å angi `-` (minus) foran linjereferansen (lokalid).

                externalValue: 'https://raw.githubusercontent.com/kartverket/SFKB-API/master/spec/examples/polygon/ArealressursFlate_enkel.xml'
              multipleLinesPolygon:
                summary: Eksempel på uthentet flate som refererer flere avgrensningslinjer der den ene bruker linjen i motsatt retning
                description: |
                  Representasjonspunktet som ligger inne i flaten ligger i `<app:posisjon>` som `<gml:Point>`.

                  TODO: gml:id : Lenkene til avgrensningslinjer (bruker linjenes lokalid) ligger i `geometry_properties` under `exterior`. 

                  Ytre avgrensningslinjer i en flate må ha retning mot klokka (CCW) og indre avgrensningslinjer må ha retning med klokka.
                  Det betyr at noen av linjene som brukes må brukes i motsatt retning - TODO: gml:id dette gjøres ved å angi `-` (minus) foran linjereferansen (lokalid).

                externalValue: 'https://raw.githubusercontent.com/kartverket/SFKB-API/master/spec/examples/polygon/ArealressursFlate.xml'
            application/vnd.kartverket.sosi+json; version=1.0:
             schema:
              type: object
             examples: 
              singlePoint:
                summary: | 
                  Eksempel på uthentet punkt
                externalValue: 'https://raw.githubusercontent.com/kartverket/SFKB-API/master/spec/examples/point/Bygning.json'
              singleLineString:
                summary: |
                  Eksempel på uthentet linje
                externalValue: 'https://raw.githubusercontent.com/kartverket/SFKB-API/master/spec/examples/linestring/Mønelinje.json'
              singleArc:
                summary: Eksempel på uthentet bue
                description: |
                  En bue beskrives av tre punkter (første, midtre og siste), men standarden GeoJSON har ingen egen type for bue.
                  
                  For å støtte enkel lesing/tegning av buer med eksisterende verktøy som støtter standard GeoJSON, ligger en bue derfor som en "vanlig" linje med `is_circular=true` i `geometry_properties` og flere punkter langs linjen som beskriver buen.
                  
                  Ved oppdatering av buen - eller dersom klienten vil tegne eksakte buer - må klienten forholde seg til første, midtre og siste punkt (og kan da fjerne/overse de andre punktene).
                externalValue: 'https://raw.githubusercontent.com/kartverket/SFKB-API/master/spec/examples/linestring/RpFormålGrense.json'
              simplePolygon:
                summary: Eksempel på uthentet flate som refererer én enkel avgrensningslinje
                description: |
                  Representasjonspunktet som ligger inne i flaten ligger i `geometry_properties` som `position`.

                  Lenkene til avgrensningslinjer (bruker linjenes lokalid) ligger i `geometry_properties` under `exterior`. 

                  Ytre avgrensningslinjer i en flate må ha retning mot klokka (CCW) og indre avgrensningslinjer må ha retning med klokka.
                  Det betyr at noen av linjene som brukes må brukes i motsatt retning - dette gjøres ved å angi `-` (minus) foran linjereferansen (lokalid).

                externalValue: 'https://raw.githubusercontent.com/kartverket/SFKB-API/master/spec/examples/polygon/ArealressursFlate_enkel.json'
              multipleLinesPolygon:
                summary: Eksempel på uthentet flate som refererer flere avgrensningslinjer der den ene bruker linjen i motsatt retning
                description: |
                  Representasjonspunktet som ligger inne i flaten ligger i `geometry_properties` som `position`.

                  Lenkene til avgrensningslinjer (bruker linjenes lokalid) ligger i `geometry_properties` under `exterior`. 

                  Ytre avgrensningslinjer i en flate må ha retning mot klokka (CCW) og indre avgrensningslinjer må ha retning med klokka.
                  Det betyr at noen av linjene som brukes må brukes i motsatt retning - dette gjøres ved å angi `-` (minus) foran linjereferansen (lokalid).

                externalValue: 'https://raw.githubusercontent.com/kartverket/SFKB-API/master/spec/examples/polygon/ArealressursFlate.json'
              multiplePolygonsSharedLine:
                summary: Eksempel på uthentede flater som refererer samme avgrensningslinje der én av flatene også har hull
                description: |
                  Representasjonspunktet som ligger inne i flaten ligger i `geometry_properties` som `position`.

                  Lenkene til avgrensningslinjer (bruker linjenes lokalid) ligger i `geometry_properties` under `exterior`. 
                  
                  Lenkene til indre avgrensningslinjer ligger i `geometry_properties` under `interiors` (liste av liste av linjenes lokalid). 

                  Ytre avgrensningslinjer i en flate må ha retning mot klokka (CCW) og indre avgrensningslinjer må ha retning med klokka.
                  Det betyr at noen av linjene som brukes må brukes i motsatt retning - dette gjøres ved å angi `-` (minus) foran linjereferansen (lokalid).

                externalValue: 'https://raw.githubusercontent.com/kartverket/SFKB-API/master/spec/examples/polygon/ArealressursFlater.json'            
        '401':
          description: Gyldig autentisering av brukeren mangler eller er ugyldig
        '406':
          description: Formatet klienten ønsker på data er ugyldig. Klienten har f.eks en ugyldig Accept-header og kan ikke motta data på et format som serveren kan levere
        '403':
          description: Ugyldig brukernavn og/eller passord
        '404':
          description: Fant ikke angitt dataset
        '500':
          description: Intern feil på serveren
        '501':
          description: Intern feil på serveren (kallet er ikke implementert)
        '503':
          description: Intern feil på serveren (tjenesten er utilgjengelig)
    post:
      tags:
       - features
      summary: Endre features i et dataset
      description: >-
        Henter en liste over alle dataset som brukeren har lese- eller skrivetilgang til.
      operationId: updateDatasetFeatures
      parameters:
        - $ref: '#/components/parameters/clientHeaderParam'
        - $ref: '#/components/parameters/datasetIdParam'
        - $ref: '#/components/parameters/lockingParam'
        - $ref: '#/components/parameters/crsEPSGParam'
        - $ref: '#/components/parameters/crsNormalizedForVisualizationParam'
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/vnd.kartverket.sosi+wfs-t; version=1.0:
            schema:
              type: object
          application/vnd.kartverket.sosi+json; version=1.0:
            schema:
              type: object
            examples: 
              singlePoint:
                summary: Eksempel på oppdatering av punkt
                description: | 
                  Den eneste forskjellen fra uthentet punkt i innholdet er `update : { action : "Replace" }` som angir at objektet skal erstattes.

                  Action kan være `Create`, `Replace` eller `Erase`. 
                  Ved `Replace` eller `Erase` med `user_lock` må objektet være hentet ut med `user_lock` før det kan endres.
                externalValue: 'https://raw.githubusercontent.com/kartverket/SFKB-API/master/spec/examples/point/Bygning_replace.json'
              simplePolygon:
                summary: Eksempel på oppdatering av flate som refererer én enkel avgrensningslinje
                description: |
                  Den eneste forskjellen fra uthentet punkt i innholdet er `update : { action : "Replace" }` som angir at objektet skal erstattes.

                  Action kan være `Create`, `Replace` eller `Erase`. 
                  Ved `Replace` eller `Erase` med `user_lock` må objektet være hentet ut med `user_lock` før det kan endres.

                  Representasjonspunktet som ligger inne i flaten ligger i `geometry_properties` som `position`.

                  Lenkene til avgrensningslinjer (bruker linjenes lokalid) ligger i `geometry_properties` under `exterior`. 

                  Ytre avgrensningslinjer i en flate må ha retning mot klokka (CCW) og indre avgrensningslinjer må ha retning med klokka.
                  Det betyr at noen av linjene som brukes må brukes i motsatt retning - dette gjøres ved å angi `-` (minus) foran linjereferansen (lokalid).

                  Legg merke til at det sendes inn endring på både flaten og linjen som brukes i avgrensningen. Dette er nødvendig for å ivareta delt geometri.

                externalValue: 'https://raw.githubusercontent.com/kartverket/SFKB-API/master/spec/examples/polygon/ArealressursFlate_enkel_replace.json'
              multiplePolygonsSharedLine:
                summary: Eksempel på oppdatering av avgrenseningslinje som refereres av to flater
                description: |
                  Den eneste forskjellen fra uthentet punkt i innholdet er `update : { action : "Replace" }` som angir at objektet skal erstattes.

                  Action kan være `Create`, `Replace` eller `Erase`. 
                  Ved `Replace` eller `Erase` med `user_lock` må objektet være hentet ut med `user_lock` før det kan endres.

                  Representasjonspunktet som ligger inne i flaten ligger i `geometry_properties` som `position`.

                  Lenkene til avgrensningslinjer (bruker linjenes lokalid) ligger i `geometry_properties` under `exterior`. 
                  
                  Lenkene til indre avgrensningslinjer ligger i `geometry_properties` under `interiors` (liste av liste av linjenes lokalid). 

                  Ytre avgrensningslinjer i en flate må ha retning mot klokka (CCW) og indre avgrensningslinjer må ha retning med klokka.
                  Det betyr at noen av linjene som brukes må brukes i motsatt retning - dette gjøres ved å angi `-` (minus) foran linjereferansen (lokalid).

                  Legg merke til at det kun sendes inn endring på begge flatene og linjen med endring (punkt 2 i geometrien er endret fra `6.192145518765789,64.8340495192154` til `6.1921,64.8340496`) som er delt mellom dem og brukes i avgrensningen. Dette er nødvendig for å ivareta delt geometri.

                externalValue: 'https://raw.githubusercontent.com/kartverket/SFKB-API/master/spec/examples/polygon/ArealressursFlater_replace.json'   

           
      responses: #TODO: valideringsfeil
        '200':
          description: OK
          content:
            application/vnd.kartverket.ngis.edit_features_summary+json:
              schema:
                type: object
                properties:
                  features_created:
                    type: integer
                    example: 10
                  features_replaced:
                    type: integer
                    example: 2
                  features_erased:
                    type: integer
                    example: 5
        '401':
          description: Gyldig autentisering av brukeren mangler eller er ugyldig
        '403':
          description: Ugyldig brukernavn og/eller passord
        '404':
          description: Fant ikke angitt dataset
        '406':
          description: Formatet klienten ønsker på data er ugyldig. Klienten har f.eks en ugyldig Accept-header og kan ikke motta data på et format som serveren kan levere
        '500':
          description: Intern feil på serveren
        '501':
          description: Intern feil på serveren (kallet er ikke implementert)
        '503':
          description: Intern feil på serveren (tjenesten er utilgjengelig)

  /datasets/{datasetId}/features/{lokalId}:
    get:
      tags:
       - features
      summary: Hent ut en bestemt feature fra et dataset
      description: >-
        Henter ut en bestemt feature med mulighet for å få med refererte objekter for redigering.
      operationId: getDatasetFeature
      parameters:
        - $ref: '#/components/parameters/clientHeaderParam'
        - $ref: '#/components/parameters/datasetIdParam'
        - $ref: '#/components/parameters/lokalIdParam'
        - $ref: '#/components/parameters/lockingParam'
        - $ref: '#/components/parameters/referencesParam'
        - $ref: '#/components/parameters/limitParam'
        - $ref: '#/components/parameters/crsEPSGParam'
        - $ref: '#/components/parameters/crsNormalizedForVisualizationParam'
      responses:
        '200':      # Response
          description: OK
          content: # Response body
            application/vnd.kartverket.sosi+gml; version=1.0:
              schema:
                type: object
            application/vnd.kartverket.sosi+json; version=1.0:
              schema:
                type: object
        '401':
          description: Gyldig autentisering av brukeren mangler eller er ugyldig
        '403':
          description: Ugyldig brukernavn og/eller passord
        '404':
          description: Fant ikke angitt dataset
        '406':
          description: Formatet klienten ønsker på data er ugyldig. Klienten har f.eks en ugyldig Accept-header og kan ikke motta data på et format som serveren kan levere
        '500':
          description: Intern feil på serveren
        '501':
          description: Intern feil på serveren (kallet er ikke implementert)
        '503':
          description: Intern feil på serveren (tjenesten er utilgjengelig)
  /datasets/{datasetId}/features/{lokalId}/attributes:
    get:
      tags:
       - features
      summary: Hent ut egenskapene til en bestemt feature fra et dataset
      description: >-
        Henter ut alle egenskapene til en bestemt feature.
      operationId: getDatasetFeatureAttributes
      parameters:
        - $ref: '#/components/parameters/datasetIdParam'
        - $ref: '#/components/parameters/lokalIdParam' 
      responses:
        '200':      # Response
          description: OK
          content: # Response body
            application/vnd.kartverket.ngis.attributes+json; version=1.0:
             schema:
              type: object
             examples:
              singleLineStringAttributes:
                summary: Eksempel på egenskaper til linje
                externalValue: 'https://raw.githubusercontent.com/kartverket/SFKB-API/master/spec/examples/linestring/Mønelinje.attributes.json'

        '401':
          description: Gyldig autentisering av brukeren mangler eller er ugyldig
        '403':
          description: Ugyldig brukernavn og/eller passord
        '404':
          description: Fant ikke angitt dataset
        '406':
          description: Formatet klienten ønsker på data er ugyldig. Klienten har f.eks en ugyldig Accept-header og kan ikke motta data på et format som serveren kan levere
        '500':
          description: Intern feil på serveren
        '501':
          description: Intern feil på serveren (kallet er ikke implementert)
        '503':
          description: Intern feil på serveren (tjenesten er utilgjengelig)
    put:
      tags:
       - features
      summary: Endre egenskapene til en bestemt feature i et dataset
      description: >-
        Oppdaterer alle egenskapene til en bestemt feature i et dataset.
      operationId: updateDatasetFeatureAttributes
      parameters:
        - $ref: '#/components/parameters/datasetIdParam'
        - $ref: '#/components/parameters/lokalIdParam'
      requestBody:
        required: true
        content:
          application/vnd.kartverket.ngis.attributes+json; version=1.0:
           schema:
            type: object 
           examples:
            singleLineStringAttributes:
              summary: Eksempel på egenskaper til linje
              externalValue: 'https://raw.githubusercontent.com/kartverket/SFKB-API/master/spec/examples/linestring/Mønelinje.attributes.json'  
      responses:
        '200':
          description: OK
          content:
            application/vnd.kartverket.ngis.attributes+json; version=1.0:
             schema:
              type: object  
             examples:
              singleLineStringAttributes:
                summary: Eksempel på egenskaper til linje
                externalValue: 'https://raw.githubusercontent.com/kartverket/SFKB-API/master/spec/examples/linestring/Mønelinje.attributes.json'

        '401':
          description: Gyldig autentisering av brukeren mangler eller er ugyldig
        '403':
          description: Ugyldig brukernavn og/eller passord
        '404':
          description: Fant ikke angitt dataset
        '406':
          description: Formatet klienten ønsker på data er ugyldig. Klienten har f.eks en ugyldig Accept-header og kan ikke motta data på et format som serveren kan levere
        '500':
          description: Intern feil på serveren
        '501':
          description: Intern feil på serveren (kallet er ikke implementert)
        '503':
          description: Intern feil på serveren (tjenesten er utilgjengelig)
  /datasets/{datasetId}/locks:
    get:
      tags:
       - locks
      summary: Hent informasjon om brukerens låste features i et bestemt dataset.
      description: |
        Henter bl.a. informasjon om hvilke objekter brukeren har låst i et bestemt dataset.
      operationId: getDatasetLocks
      parameters:
        - $ref: '#/components/parameters/clientHeaderParam'
        - $ref: '#/components/parameters/datasetIdParam'
        - $ref: '#/components/parameters/lockingParam'
      responses:
        '200':      # Response
          description: OK
          content:  # Response body
            application/vnd.kartverket.ngis.locks+json:  # Media type
             schema: 
               $ref: '#/components/schemas/Locks'    # Reference to object definition
        '401':
          description: Gyldig autentisering av brukeren mangler eller er ugyldig
        '403':
          description: Ugyldig brukernavn og/eller passord
        '404':
          description: Fant ikke angitt dataset
        '406':
          description: Formatet klienten ønsker på data er ugyldig. Klienten har f.eks en ugyldig Accept-header og kan ikke motta data på et format som serveren kan levere
    delete:
      tags:
        - locks
      summary: Fjerne alle låser brukeren har i et bestemt dataset
      description: |
        Fjerne alle låser brukeren har i et bestemt dataset
      operationId: deleteDatasetLocks        
      parameters:
        - $ref: '#/components/parameters/clientHeaderParam'
        - $ref: '#/components/parameters/datasetIdParam'
        - $ref: '#/components/parameters/lockingParam'
      responses:
        '204': # Success
          description: No Content
        '401':
          description: Gyldig autentisering av brukeren mangler eller er ugyldig
        '403':
          description: Ugyldig brukernavn og/eller passord
        '404':
          description: Fant ikke angitt dataset
components:
  securitySchemes:
    basicAuth:     # <-- arbitrary name for the security scheme
      type: http
      scheme: basic
      description: |
        Brukernavn og passord som er gyldige mot dataset som skal brukes. 
        For QMS er dette brukernavn og passord mot oppgaven.
  schemas:
    DatasetList:
      type: array
      items:
        type: object
        properties:
          id:
            type: string
            format: uuid
          name:
            type: string
          access:
            type: string
            enum: [read_only, read_write]
      example:
        - id: '07b59e3d-a4b6-4bae-ac4c-664d3dc3d778'
          name: 'AR5'
          access: read_write
        - id: '08b59e3d-a4b6-4bae-ac4c-664d3dc3d779'
          name: 'Bygning'
          access: read_only
        - id: '09b59e3d-a4b6-4bae-ac4c-664d3dc3d659'
          name: 'DEK'
          access: read_only
    Dataset:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        resolution:
          type: number
          format: double
        crs_EPSG:
          type: integer
        dataset_last_modified:
          type: string
          format: datetime
        schema_url:
          type: string
          format: uri
        access:
          type: string
          enum: [read_only, read_write]
        bbox: 
          $ref: '#/components/schemas/BoundingBox'
    Locks:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer # TODO: Denne brukes ikke for brukerlåser, men trengs for andre låser i fremtiden.
          username:
            type: string
          features:
            type: array
            items:
              type: object
              properties:
                lokalid:
                  type: string
                  format: uuid
      example:
        - id: 15003
          username: joeuser
          features:
            - lokalid: '933f0223-2598-485b-b886-3c69650b22b0'
            - lokalid: 'ddb688c3-b2d9-47eb-93d2-cc4704b6394c'
    BoundingBox:
      type: array
      minItems: 4
      maxItems: 6
      items:
        type: number
      example: [10.0, 10.0, 20.0, 20.0]
    # Schema for error response body
    Error:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: integer
        detail:
          type: string
        instance:
          type: string
      required:
        - type
        - title
        - detail
       
  parameters:
    clientHeaderParam:
      in: header
      name: X-Client-Product-Version
      schema:
        type: string
      required: true
      description: Brukes for å kunne identifisere klienten som er brukt
      example: 'ExampleApp 10.0.0 (Build 54321)'
    datasetIdParam:
      in: path
      name: datasetId
      schema:
        type: string
        format: uuid
      required: true
      description: UUID of the dataset to get
      example: dc3507da-a95f-4482-b762-f140f5a11788
    cursorParam:
      in: query
      name: cursor
      schema:
        type: string
        format: byte
      description: Brukes til porsjonering av data
    bboxParam:
      in: query
      name: bbox
      style: form
      explode: false
      schema:
        $ref: '#/components/schemas/BoundingBox'
      examples:
        smallbbox:
          summary: Et 10x10m vindu
          description: |
            NB! Koordinatene må være i dataset'ets koordinatsystem eller angi crs_EPSG-parameteret
          value: [10.0, 100.0, 20.0, 200.0] # ?bbox=10.0,100.0,20.0,200.0
      description: |
        Henter ut objekter i et bestemt område (angitt med et rektangel)
        
        Dette kan være aktuelt for å få ut alle objekter som ikke er direkte knyttet til et objekt, som f.eks mønelinje og takkant til en bygning.
        
        Merk: I kombinasjon med `bbox` blir alltid `references` satt til `none`
    crsEPSGParam:
      in: query
      name: crs_EPSG
      schema:
        type: integer
      description: |
        Angir EPSG-kode for koordinatsystemet til koordinatene som sendes inn i spørringen (f.eks i bbox), som sendes inn som data, og som sendes tilbake. Påkrevd dersom bbox-parameteret brukes.
      examples: 
        epsg5975_NN2000:
          value: 5975
          summary: ETRS89 (EUREF89) i UTM zone 35N med høydeverdier angitt i NN2000
        epsg5975_NN1954:
          value: 6175
          summary: ETRS89 (EUREF89) i UTM zone 35N med høydeverdier angitt i NN1954
        epsg5975:
          value: 25835
          summary: ETRS89 (EUREF89) i UTM zone 35N uten høyde
        epsg5973_NN2000:
          value: 5973
          summary: ETRS89 (EUREF89) i UTM zone 33N med høydeverdier angitt i NN2000
        epsg5973_NN1954:
          value: 6173
          summary: ETRS89 (EUREF89) i UTM zone 33N med høydeverdier angitt i NN1954
        epsg5973:
          value: 25833
          summary: ETRS89 (EUREF89) i UTM zone 33N uten høyde
        epsg5972_NN2000:
          value: 5972
          summary: ETRS89 (EUREF89) i UTM zone 32N med høydeverdier angitt i NN2000
        epsg5972_NN1954:
          value: 6172
          summary: ETRS89 (EUREF89) i UTM zone 32N med høydeverdier angitt i NN1954
        epsg5972:
          value: 25832
          summary: ETRS89 (EUREF89) i UTM zone 32N uten høyde
        epsg4258_NN2000:
          value: 5942
          summary: ETRS89 (EUREF89) i geografiske koordinater med høydeverdier angitt i NN2000
        epsg4258_NN1954:
          value: 6144
          summary: ETRS89 (EUREF89) i geografiske koordinater med høydeverdier angitt i NN1954
        epsg4258:
          value: 4258
          summary: ETRS89 (EUREF89) i geografiske koordinater uten høyde
    crsNormalizedForVisualizationParam:
      in: query
      name: normalized_for_visualization
      schema:
        type: boolean
      description: |
        Angir at rekkefølgen på x- og y-aksen skal være snudd mot det som er spesifisert i EPSG-koden.
    referencesParam:  
      in: query
      name: references
      schema:
        type: string
        enum: [none, direct, all]
      required: true
      description: |
        Angir hvilke refererte features som skal hentes ut i tillegg til feature det spørres direkte etter med lokalid.

        Punkter har ingen referanser, og parameteret påvirker derfor ikke uthenting av et punkt.

        `none` - Ingen refererte features hentes ut. Ingen ekstra features låses.
        - Flater får *ikke* med linje-features til avgrensningskurver.

        `direct` - Features med direkte referanser hentes ut. Kun direkte referanser låses.
        - Kurver får med features til flater som bruker kurven i avgrensningen, samt de andre linje-features til avgrensningskurvene i flatene. Både kurven og alle flatene låses, men ikke de andre linje-features i avgrensningen i flatene.
        - Flater får med alle linje-features til avgrensningskurvene i flaten. Kun flaten låses.

        `all` - Features med direkte og indirekte tilhørende referanser hentes ut. Alle referanser som hentes ut låses.
        - Kurver får i tillegg til referanser fra `direct` også med:
          - flate-features som har avgrensningskurver som begynner eller slutter i valgt linjes endepunkter 
          - linje-features i flate-features i forrige pkt som begynner eller slutter i valgt linjes endepunkter

        - Flater får samme referanser som i `direct`. Både flaten og alle avgrensningskurvene låses.
    lockingParam:
      in: query
      name: locking_type
      schema:
        type: string
        enum: [user_lock] # future: lock_id,optimistic_locking
      description: |
        Angir låsetype som skal brukes (foreløpig er kun `user_lock` støttet). Krever at brukeren har skrivetilgang mot dataset'et.
        
        *user_lock*

        Hver bruker har én lås per dataset. Hver gang data hentes ut med `user_lock` legges objektene til denne låsen. 
        Alle objekter i låsen låses opp neste gang brukeren skriver data til dataset'et.

        Låsen vil fjernes neste gang brukeren skriver data til dataset'et med `user_lock`, eller dersom låsen slettes.
    lokalIdParam:
      in: path
      name: lokalId
      schema:
        type: string
        format: uuid
      required: true
      description: Identifikasjon.Lokalid til objektet
    limitParam:
      in: query
      name: limit
      schema:
        type: integer
        format: int32
        minimum: 1
      description: |
        Angir grense for antall objekter som skal returneres av gangen. Hvert dataset har en øvre grense som vil overstyre det klienten ber om, eller brukes dersom klienten ikke angir dette parameteret.
        
        Dersom resultatet inneholder flere objekter enn grensen, vil responsen inneholde en lenke med `rel=next` i [`Link`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Link)-header. Denne lenken skal brukes direkte (det er ikke tillatt å tolke lenken ytterligere) for å hente ut neste del av resultatet, som vil være tilsvarende. De siste objektene fra operasjonen er hentet ut når resultatet ikke lenger inneholder en [`Link`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Link)-header med `rel=next`.
